name:                deltafetch
version:             0.1.0.0
github:              "ruzen42/deltafetch"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           "2025 @Ruzen42"

extra-source-files:
- README.md
- CHANGELOG.md

category:            System 

description:         Please see the README on GitHub at <https://github.com/ruzen42/deltafetch#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - directory
    - process
    - ansi-terminal
    - parsec
    - yaml
    - text 
    - bytestring
 
executables:
  deltafetch:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deltafetch
    - ansi-terminal
    - optparse-applicative

tests:
  deltafetch-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deltafetch
